### ISSUE TITLE
[question] Comparsion to other SS clients

### ISSUE THREAD

**Issue by dimqua** [nange/easyss#10]
Could you pls describe what are the main differences (and benefits) from official SS clients? The program seems to be intended to non-tech users, but it's not clear (for me) why they should choose it instead.

**Comment by nange** [comment]
Hi, sorry for reply  so late.  
The easyss contains client-server and remote-server. And the protocol incompatible with  official SS. 
The easyss protocol is based on ```http2```, and use ```tcp connection pool``` to reduce network latency.
