### ISSUE TITLE
优化连接池过期连接使用问题

### ISSUE THREAD

**Issue by nange** [nange/easyss#9]
目前当一个代理请求发起时，会从连接池中取一个tcp连接，如果此连接已经失效，则本次请求会直接返回错误。 
此逻辑可以优化为：如果发现此连接已经失效(通过err信息判断等方式)，则内部能够重新获取一个连接重试，并关闭失效连接，避免直接返回错误。

**Comment by childeYin** [comment]
我试试~~

**Comment by nange** [comment]
Fixed by: e841111ed5486b70a77d3bb2a29445b2493e77f5
